#!/usr/bin/env bash
# Bassh script that installs Nginx web server and configure it to listen on port 80
# It then prints "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
