#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend darktracer.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 530424-web-01 52.91.148.87:80
        server 530424-web-02 54.237.125.26:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
